### ISSUE TITLE
Update to work with new clingo version.

### ISSUE THREAD

**Issue by rkaminsk** [potassco/telingo#8]
Telingo does not work with the Python module in the upcoming clingo 5.5. This mainly concerns code involving the AST. The code should be relatively easy to adjust.

**Comment by tortinator** [comment]
Hallo @rkaminsk, I just talked to @susuhahnml and she'd be happy to address this issue as an exercise to learn more about `telingo` and `clingo`'s API - thanks for thinking of it! @tortinator

**Comment by rkaminsk** [comment]
It should not be that difficult. There is of course some legacy cruft because telingo was the first project to really use the AST API. Also telingo has quite some unit tests that should hopefully point to all the places that have to be adjusted.
